producers:

- name:   Kristin Eugenio
  email:  kristin.eugenio@generalassemb.ly
- name:   Stephanie Morillo
  email:  stephanie.morillo@generalassemb.ly

instructors:

- name:   Max Cantor
  email:  max.cantor@generalassemb.ly
- name:   David Han
  email:  david.han@generalassemb.ly
- name:   Phillip Lamplugh
  email:  phillip.lamplugh@generalassemb.ly

locations:

- name:     GA West
  address:  10 E 21st, New York, NY 10010
  hours:    8am to 8pm
- name:     GA East
  address:  902 Broadway, New York, NY 10010
  hours:    8am to 8pm
- name:     GA Union Square
  address:  41 Union Square West, New York, NY 10010
  hours:    8am to 8pm

office_hours:

- mondays:    6pm to 8pm
  instructor: Max
- tuesdays:   6pm to 8pm
  instructor: Phil
- wednesdays: 6pm to 8pm
  instructor: David

homework_lead: davidhan527