producers:

- name:   Kristin Eugenio
  email:  kristin.eugenio@generalassemb.ly
- name:   Stephanie Morillo
  email:  stephanie.morillo@generalassemb.ly

instructors:

- name:   Omar Delarosa
  email:  omar@ga.co
- name:   Neel Patel
  email:  neel.patel@ga.co
- name:   Keri Toksu
  email:  keri.toksu@ga.co
- name:   Max Cantor
  email:  max.cantor@generalassemb.ly

locations:

- name:     GA West
  address:  10 E 21st, New York, NY 10010
  hours:    8am to 8pm
- name:     GA East
  address:  902 Broadway, New York, NY 10010
  hours:    8am to 8pm
- name:     GA Union Square
  address:  41 Union Square West, New York, NY 10010
  hours:    8am to 8pm